# Generated by Django 3.2.5 on 2021-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
